package com.sabkuchfresh.analytics;

/**
 * Created by shankar on 3/2/17.
 */

public interface GAAction {
	String HOME = "Home ";
	String DELIVERY_ADDRESS = "Delivery Address ";
	String ADD_ONS = "Add ons ";
	String CHECKOUT = "Checkout ";
	String DELIVERY_SLOT = "Delivery Slot ";
	String SUBSCRIPTION = "Subscription ";
	String WALLET = "Wallet ";
	String ORDER_PLACED = "Order Placed ";
	String REFERRAL_POPUP = "Referral popup ";
	String FEEDBACK = "Feedback ";
	String ORDER_STATUS = "Order Status ";
	String SUPPORT = "Support ";
	String MODIFIED = "Modified ";
	String OFFER = "Offer ";

	String CLICKED = "Clicked ";
	String BACK = "Back ";
	String BUTTON = "Button ";
	String ENTERED = "Entered ";
	String ADDRESS_BOX = "Address Box ";
	String SELECTED = "Selected ";
	String CURRENT_LOCATION = "Current Location ";
	String CHOOSE_ON_MAP = "Choose on Map ";
	String SAVED_PLACES = "Saved places ";
	String SUGGESTED_PLACES = "Suggested places ";
	String ITEM = "Item ";
	String ADDED = "Added ";
	String INCREASED = "Increased ";
	String DECREASED = "Decreased ";
	String CART = "Cart ";
	String VIEW_EXPANDED = "View Expanded ";
	String EMPTIED = "Emptied ";
	String ADDED_TO_CART = "Added to Cart ";
	String EXISTING = "Existing ";
	String SKIP_AND_PROCEED = "Skip and Proceed ";
	String PAY_SLIDER = "Pay Slider ";
	String STARTED = "Started ";
	String ENDED = "Ended ";
	String NOTES = "Notes ";
	String LATER = "Later ";
	String IN_RIDE = "In Ride ";
	String REFER = "Refer ";
	String THUMB_UP = "Thumbs Up ";
	String THUMB_DOWN = "Thumbs Down ";
	String ISSUE = "Issue ";
	String COMMENT = "Comment ";
	String CANCELLED = "Cancelled ";
	String ORDER = "Order ";
	String NEED_HELP = "Need help ";
	String TICKET_RAISED = "Ticket raised ";
	String AUTO = "Auto ";
	String REQUESTED = "Requested ";
	String REQUEST = "Request ";
	String PICKUP = "Pickup ";
	String LOCATION = "Location ";
	String DESTINATION = "Destination ";
	String UPDATED = "Updated ";
	String OPTION = "Option ";
	String NO = "No ";
	String DIALOG = "Dialog ";
	String REFERRAL = "Referral ";
	String INVITE = "Invite ";
	String FRIENDS = "Friends ";
	String FARE_DETAILS = "Fare Details ";
	String FARE_ESTIMATE = "Fare Estimate ";
	String RIDE_ACCEPTED_PUSH = "Ride Accepted Push ";
	String CHAT = "Chat ";
	String DRIVER_ENROUTE = "Driver Enroute ";
	String CALL = "Call ";
	String WAITING_FOR_DRIVER = "Waiting for Driver ";
	String RIDE = "Ride ";
	String IN_PROGRESS = "In Progress ";
	String HELP = "Help ";
	String POPUP = "Popup ";
	String SEND_RIDE_STATUS = "Send Ride Status ";
	String ENABLE_EMERGENCY_MODE = "Enable Emergency Mode ";
	String IN_APP_SUPPORT = "In App Support ";
	String SEND = "Send ";
	String FINISHED = "Finished ";
	String GET = "Get ";
	String TNC = "TnC ";
	String VIEW_INVOICE = "View Invoice ";
	String PICKUP_LOCATION_DIFFERENT_FROM_CURRENT_LOCATION = "Pickup location different from current location ";
	String OK = "OK ";
	String CANCEL = "Cancel ";
}
