package com.sabkuchfresh.feed.ui.api;

/**
 * Created by Parminder Singh on 3/28/17.
 */


public enum ApiName {

    GENERATE_FEED_API,
    FETCH_FEED_DETAILS,
    POST_FEED,
    COMMENT_ON_FEED,
    LIKE_FEED,
    DELETE_FEED,
    SUGGEST_RESTAURANT,
    SYNC_CONTACTS,
    EDIT_FEED,
    DELETE_COMMENT,
    UNLIKE_FEED,
    REGISTER_FOR_FEED,
    COUNT_NOTIFICATION,
    SET_HANDLE_API,
    FEED_UPDATE_NOTIFICATION,
    GET_HANLDE_SUGGESTIONS,
    CITY_INFO_API,

    USER_CLICK_EVENTS,
    ANYWHERE_PLACE_ORDER,
    INITIATE_RIDE_END_PAYMENT
}
